services:
  db:
    image: postgres:17
    container_name: nest-challenge
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
